---
title: Integrated farming and global warming mitigation in Brazil
author: 
  - name: Hugo Tameirão Seixas
    email: seixas.hugo@protonmail.com
    url: hugotseixas.com
    affiliations:
      - name: State University of Campinas
toc: true
toc-title: Contents
format: 
  html:
    theme: lux
page-layout: article
editor: visual
bibliography: references.bib
link-citations: true
abstract: "There is a high expectation in the reduction of liquid greenhouse gases in Brazil by the implementation of integrated crop-livestock-forestry systems. The foundation of such expectation relies in the hyphothesis that these systems are capable of storing more above and below ground carbon, in relation to conventional farming systems, due to the presence of trees. However, that are not robust estimates about the pottential of these systems to store carbon in a national scale, and usually point estimates are used to extrapolate carbon sequestration. In order to improve the representation of carbon sequestration by integrated crop-livestock-forestry systems, this project aims to use published data to develop a spatially explicit model to estimate carbon fluxes in Brazil."
---

```{r}
#| include: false
  library(nomnoml)
```

------------------------------------------------------------------------

# Introduction

The implementation of integrated crop-livestock-forestry (ICLF) systems in Brazil are expected to sequester enough carbon to contribute to reduce annual liquid carbon emissions. Despite the expectations, there are not clear estimates of the magnitude of reductions of liquid emissions caused by ICLF expansion. Field studies show contrasting results. @Valani2022 observed a higher organic carbon content in the soil in relation to conventional grazing and other integrated systems. @Bieluczyk2020 field measurements did not show clear differences between extensive grazing and ICLF soil organic matter, with highly temporal heterogeneity in observations. @Silva2018837 found inconsistent differences of soil total organic carbon between pasture and ILPF system due to high heterogeneity of observations along the soil layers, and observed small differences between agriculture and integrated system, in which the agriculture presented higher carbon stocks. @Oliveira2018105 found higher amounts of soil organic carbon of two ICLF systems and continuous pasture areas, there were also observed differences between the two integrated systems.

Unfortunately, estimates of carbon sequestration by ICLF at larger scales usually use point estimates, which can severely bias the results towards one direction. @Azevedo_2018 used a CO<sub>2</sub>-eq removal factor of -6.24 t CO<sub>2</sub>-eq ha<sup>-1</sup> y<sup>-1</sup>, which was extracted from one experiment comparing integrated crop-livestock (ICL) systems to pasture [@Carvalho_2010], and did not observe consistent differences between these types of systems. The removal factor was then extrapolated over estimated ILPF area, this simplification is the best guess that Brazil have over the potential of integrated systems in reducing liquid emissions. In face of such scenario, this study aims to generate estimations of CO<sub>2</sub>-eq removal accounting for variation in many aspects, soil attributes, ICLF system characteristics, species used, spacing and climate. We expect that such estimations will provide more realistic ranges of possible outcomes in a diverse set of future scenarios of ICLF expansion in Brazil.

------------------------------------------------------------------------

# Objectives

1.  What are the management practices that lead to the best com- promise between carbon sequestration and financial revenue for agricultural land under ICLFS?

2.  Can indirect land-use and land-cover changes, especially land sparing under expansion of ICLFS, improve the net carbon budget of this agricultural system?

3.  Does the prioritization of the provision of ecosystem services other than carbon storage imply in changes of productivity of ICLFS?

4.  Can further expansion of ICLFS, beyond Brazil's NDC target, replace the afforestation targets pledged in the scientific literature for the tropics in terms of carbon storage, provision of ecosystem services and economic revenue?

------------------------------------------------------------------------

# Materials and Methods

In order to achieve the proposed objective, the work will be divided in four major parts:

1.  ICLFS management scenario elaboration;

2.  Adaptation and application of the modeling framework to ICLFS;

3.  Estimate the carbon balance, ecosystem services, and economic evaluation based on outputs from modeling framework;

4.  Results consolidation and analysis;

```{nomnoml}
#| echo: false

# direction: down
# .box: dashed
[Start]-[Finish!]
[Finish!]-[<box>blablablablabla
           lablablablablablabla]

```

### Integrated crop-livestock-forest overview

#### Literature review

#### Experts survey

### Model projections

------------------------------------------------------------------------

# Results

------------------------------------------------------------------------

# Discussion

------------------------------------------------------------------------

# Conclusions

------------------------------------------------------------------------

# Supporting Information

# References
