---
title: "Characterization of integrated crop-livestock-forest system in Brazil"
author: "Hugo Tameirão Seixas"
format: 
  html:
    page-layout: article
    toc: true
    toc-depth: 2
number-sections: true
---

## Title and Abstract

### Identify the review as a systematic review, meta-analysis, or both

This is a systematic review

### Summarise the aims and scope of the review

The main objective of this review is to synthesize data concerning ICLF in different aspects, creating an overview of the main characteristics of the ICLF being researched in Brazil. I will analyse variables such as above and below ground productivity of the tree, pasture and crop components; livestock productivity; system management characteristics; soil attributes; GHG emissions. I will evaluate national and international research conducted inside the Brazilian territory.

### Describe the data set

The data set will be composed by a collection of relational tables, each table will describe a characteristic of the ICLF in Brazil.

### State the results of the primary outcome

### State conclusions

### State limitations

## Aims and questions

### Provide a rationale for the review

The review will be performed over any research that analysed any aspect of the ICLF in Brazil. Therefore this is a very general approach, which is feasible due to the limited amount of research in this topic. Only documents which are not explicitly about ICLF will be removed from the review.

I will extract data of a diverse number of variables, which will allow me to create an overview of the characteristics of the ICLF systems being analysed in Brazil.

### Reference any previous reviews or meta-analyses on the topic

I have not yet identified any systematic review about ICLF in Brazil.

### State the aims and scope of the review (including its generality)

In this review I will analyse studies about ICLFS in Brazil. I pretend to answer several questions:

-   Where are experiments on ICLFS being conducted?

-   What are the characteristics of these systems? (species used, fertilizers, number of individuals per hectare, duration of the production cycle...)

-   What are the fiber and food productivity in these systems?

-   What is the amount of above ground carbon (alive and dead) being accumulated?

-   What is the amount of below ground carbon being accumulated?

-   What are the emissions of green house gases related to the ICLFS?

-   What is the economic revenue from the adoption of the ICLFS?

### State the primary questions the review addresses (e.g. which moderators were tested)

### Describe whether effect sizes were derived from experimental and/or observational comparisons

## Review registration

## Eligibility criteria

## Finding studies

### Define the type of search (e.g.comprehensive search, representative sample)

### State what sources of information were sought (e.g. published and unpublished studies, personal communications)

### Include, for each database searched, the exact search strings used, with keyword combinations and Boolean operators

Scopus: TITLE-ABS-KEY(iclf OR iclfs OR crop-livestock-forestry OR crop-livestock-forest OR agrosilvipastoral OR ilpf OR lavoura-pecuária-floresta OR agrosilvipastoril) AND PUBYEAR > 1999

Embrapa: ((ICLF) OR (iclfs) OR (crop-livestock-forestry) OR (crop-livestock-forest) OR (agrosilvipastoral) OR (ilpf) OR (lavoura-pecuária-floresta) OR (agrosilvipastoril)) AND (ano-publicacao:[2000 TO *]) AND (tipo-material-sigla:"PC" OR tipo-material-sigla:"AP" OR tipo-material-sigla:"NC" OR tipo-material-sigla:"RT") AND (idioma:"Inglês" OR idioma:"Português")

### Provide enough information to repeat the equivalent search (if possible), including the timespan covered (start and end dates)

## Study selection

## Data collection process

## Data items

## Assessment of individual study quality

## Effect size measures

## Missing data

## Meta-analytic model description

## Software

## Non independence

## Meta-regression and model selection

## Publication bias and sesitivity analysis

## Clarification of post hoc analysis

## Metadata data and code

## Results of study selection process

## Sample sizes and study characteristics

## Meta-analysis

## Heterogeneity

## Meta-regression

## Outcomes of publication bias and sensitivity analyses

## Discussion

## Contributions and funding

## References
